config/routes.rb
Rails.application.routes.draw do
  get 'public/tags'
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
     get "search" => "searches#search"
    resources :users, only: [:index, :show, :edit, :update]
    resources :tags, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
  end

  resources :videos

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :tags, only: [:index, :show]
    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:index, :create, :destroy] do
        get 'post_bookmarks', to: 'bookmarks#index', as: 'user_bookmarks'
      end
    end

    devise_scope :user do
      resources :users, only: [:index, :show, :edit] do
        collection do
          get 'my_page', action: 'mypage'
          patch 'update_my_page', to: 'users#update', as: 'update_user'
          patch :withdraw
          get :bookmark_posts, to: 'bookmarks#index' # ブックマークした一覧
        end
        resource :relationships, only: [:create, :destroy]
        	get "followings" => "relationships#followings", as: "followings"
        	get "followers" => "relationships#followers", as: "followers"

      end

      post "user/guest_sign_in", to: "sessions#guest_sign_in"
    end


    resource :sessions, only: [:new, :create, :destroy]
  end 

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tags = Tag.page(params[:page]).per(15)
  end
  
  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    Tag.find(params[:id]).destroy()
    redirect_to admin_tags_path
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Posts#edit</h1>
    <p>Find me in app/views/posts/edit.html.erb</p>
    
    <h2>Post --></h2>
    <%= form_with model: @post do |post| %>
      <%= render 'form', post: post %>
    <% end %>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="row d-flex justify-content-center">
        <div class="titleK">
          <h1>タグ一覧</h1>
        </div>
      </div>
      <div class="col">
        <span class="d-flex flex-row flex-wrap">
          <% @tags.each do |tag| %>
            <div class="neko-wrap-b col-4">
              <div class="neko-box">
                ・x・
                <div class="text-center ">
                  <%= link_to "#{tag.name} (#{tag.posts.count})", admin_tag_path(tag) %>
                </div>
              </div>
            </div>
          <% end %>
        </span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col pt-5">
      <%= paginate @tags %>
    </div>
  </div>
</div>

app/views/admin/tags/show.html.erb
<div class="container">
  <div class="row">
    <div class="titleK">
      <h1><%= @tag.name %></h1>
    </div>
  </div>
  <div class="row pt-5">
    <% @tag.posts.each do |post| %>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <%= link_to post.post_content.truncate(20), admin_post_path(post) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <%= link_to admin_tag_path(@tag), method: :delete, "data-confirm" => "タグを削除しますか？" do %>
    <i class="fa-solid fa-trash-can"></i>削除
    <% end %>
  </div>
</div>