config/routes.rb
Rails.application.routes.draw do
  get 'public/tags'
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
     get "search" => "searches#search"
    resources :users, only: [:index, :show, :edit, :update]
    resources :tags, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
  end

  resources :videos

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :tags, only: [:index, :show]
    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:index, :create, :destroy] do
        get 'post_bookmarks', to: 'bookmarks#index', as: 'user_bookmarks'
      end
    end

    devise_scope :user do
      resources :users, only: [:index, :show, :edit] do
        collection do
          get 'my_page', action: 'mypage'
          patch 'update_my_page', to: 'users#update', as: 'update_user'
          patch :withdraw
          get :bookmark_posts, to: 'bookmarks#index' # ブックマークした一覧
        end
        resource :relationships, only: [:create, :destroy]
        	get "followings" => "relationships#followings", as: "followings"
        	get "followers" => "relationships#followers", as: "followers"

      end

      post "user/guest_sign_in", to: "sessions#guest_sign_in"
    end


    resource :sessions, only: [:new, :create, :destroy]
  end 

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  # dependent: :destroyでPostが削除されると同時にPostとTagの関係が削除される
  has_many :post_tags, dependent: :destroy

  # throughを利用して、post_tagsを通してtagsとの関連付け(中間テーブル)
  #   Post.tagsとすれば、Postに紐付けられたTagの取得が可能
  has_many :tags, through: :post_tags
  # いいね
  has_many :post_favorites, dependent: :destroy
  # コメント
  has_many :post_comments, dependent: :destroy
  # ブックマーク
  has_many :post_bookmarks, dependent: :destroy 
  
  has_many :bookmarked_users, through: :post_bookmarks, source: :user
  
  validates :post_content, presence: true
 


  has_many_attached :medias
  
  def bookmarked_by?(user)
    post_bookmarks.exists?(user_id: user)
  end
  
  def self.bookmark_posts(user, page, per_page) # モデル内での操作を開始
    includes(:post_favorites) # post_favorites テーブルを結合
    .where(post_favorites: { user_id: user.id }) # ユーザーがいいねしたレコードを絞り込み
    .order(created_at: :desc) # 投稿を作成日時の降順でソート
    .page(page) # ページネーションのため、指定ページに表示するデータを選択
    .per(per_page) # ページごとのデータ数を指定
  end

  def favorited_by?(user)
    post_favorites.exists?(user_id: user.id)
  end

  def save_tags(tags)

    # タグをスペース区切りで分割し配列にする
    #   連続した空白も対応するので、最後の“+”がポイント
    #tag_list = tags.split(/[[:blank:]]+/)
    tag_list = tags.split(/[[:blank:]　]+/)

    # 自分自身に関連づいたタグを取得する
    current_tags = self.tags.pluck(:name)

    # (1) 元々自分に紐付いていたタグと投稿されたタグの差分を抽出
    #   -- 記事更新時に削除されたタグ
    old_tags = current_tags - tag_list

    # (2) 投稿されたタグと元々自分に紐付いていたタグの差分を抽出
    #   -- 新規に追加されたタグ
    new_tags = tag_list - current_tags

    # tag_mapsテーブルから、(1)のタグを削除
    #   tagsテーブルから該当のタグを探し出して削除する
    old_tags.each do |old|
      # tag_mapsテーブルにあるpost_idとtag_idを削除
      #   後続のfind_byでtag_idを検索
      self.tags.delete Tag.find_by(name: old)
    end

    # tagsテーブルから(2)のタグを探して、tag_mapsテーブルにtag_idを追加する
    new_tags.each do |new|
      # 条件のレコードを初めの1件を取得し1件もなければ作成する
      # find_or_create_by : https://railsdoc.com/page/find_or_create_by
      new_post_tag = Tag.find_or_create_by(name: new)

      # tag_mapsテーブルにpost_idとtag_idを保存
      #   配列追加のようにレコードを渡すことで新規レコード作成が可能
      self.tags << new_post_tag
    end
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    else search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).per(12)
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end
  
  def post_params
    params.require(:post).permit(:post_content, medias: [])
  end
  
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 text-center pt-3">
      <div class="titleE">
        <h1>投稿一覧</h1>
      </div>
    </div>
  </div>
  <div class="box1">
    <div class="row p-3">
      <% @posts.each do |post| %>
        <div class="col-md-3 pb-3">
          <div class="card p-3">
            <div class="card-image text-center pt-3">
              <% if post.medias.attached? %>
                    <% post.medias.each do |media| %>
                      <% if media.content_type.include?('image') %>
                        <%= link_to post_path(post) do %>
                          <%= image_tag media, class: "img-fluid", size: "200x200" %>
                        <% end %>
                      <% else %>
                        <%= video_tag rails_blob_path(media), controls: true, class: "img-fluid", size: "200x200" %>
                      <% end %>
                    <% end %>
                  <% else %>
                    <%= image_tag 'no_image1.png', size: "200x200" %>
                  <% end %>
            </div>
            <div class="card-body text-center">
              <span>
                  <%=link_to post.post_content.truncate(20), admin_post_path(post.id) %>
              </span>
              <div class="col">
                <i class="fa-regular fa-comment-dots" style="color: #765047;"></i> <%= post.post_comments.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col d-flex align-items-center justify-content-center pb-3">
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class ="row d-flex justify-content-center">
    <div class="col-5 text-center">
      <div class="titleD">
        <h1>投稿</h1>
      </div>
    </div>
  </div>
  <div class="row justify-content-center pt-5">
    <% if @post.medias.attached? %>
      <% @post.medias.each do |media| %>
        <% if media.content_type.include?('image') %>
          <%= image_tag media, class: "img-fluid", size: "300x300" %>
        <% else %>
          <%= video_tag rails_blob_path(media), controls: true, class: "img-fluid", size: "300x300" %>
        <% end %>
      <% end %>
    <% else %>
      <%= image_tag 'no_image.jpg', size: "200x200" %>
    <% end %>
    <div class="row flex-column text-center p-5">
      <div class=" text-center pt-3 pb-3">
        <%= @post.post_content %>
      </div>
      <div class=" text-center pt-3 pb-5">
        <h4>タグ</h4>
        <% @post.tags.each do |tag| %>
          <li>
            <%= link_to tag.name, tag_path(tag) %>
          </li>
        <% end %>
      </div>
      <div class=" text-center pt-3 pb-3">
        <%= link_to edit_post_path(@post.id) do %>
          <i class="fa-solid fa-user-pen"></i>編集
        <% end %>
        <%= link_to post_path(@post.id), method: :delete, "data-confirm" => "投稿を削除しますか？" do %>
          <i class="fa-solid fa-trash-can"></i>削除
        <% end %>
      </div>
    </div>
  </div>
</div>