config/routes.rb
Rails.application.routes.draw do
  get 'public/tags'
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
     get "search" => "searches#search"
    resources :users, only: [:index, :show, :edit, :update]
    resources :tags, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
  end

  resources :videos

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :tags, only: [:index, :show]
    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:index, :create, :destroy] do
        get 'post_bookmarks', to: 'bookmarks#index', as: 'user_bookmarks'
      end
    end

    devise_scope :user do
      resources :users, only: [:index, :show, :edit] do
        collection do
          get 'my_page', action: 'mypage'
          patch 'update_my_page', to: 'users#update', as: 'update_user'
          patch :withdraw
          get :bookmark_posts, to: 'bookmarks#index' # ブックマークした一覧
        end
        resource :relationships, only: [:create, :destroy]
        	get "followings" => "relationships#followings", as: "followings"
        	get "followers" => "relationships#followers", as: "followers"

      end

      post "user/guest_sign_in", to: "sessions#guest_sign_in"
    end


    resource :sessions, only: [:new, :create, :destroy]
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }
  validates :introduction, length: { maximum: 100 }


  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed
  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower
  # プロフィール画像を保存できるように設定
  has_one_attached :profile_image
  # ユーザーが投稿を取得
  has_many :posts, dependent: :destroy
  # 投稿に対するいいねを取得
  has_many :post_favorites, dependent: :destroy
  # 投稿に対するコメントを取得
  has_many :post_comments, dependent: :destroy
  # 投稿に対するブックマーク
  has_many :post_bookmarks, dependent: :destroy


  # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width, height)
    if profile_image.attached?
       profile_image.variant(resize_to_limit: [width, height]).processed
    else
      'no_image1.png'
    end
  end

  # 退会済みかどうか確認
  def active_for_authentication?
    super && is_active?
  end

  # ユーザー退会済みの場合のメッセージ
  def inactive_message
    is_active? ? super : :locked
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest #find_or_create_byは、データの検索・作成を自動的に判断して処理を行うRailsのメソッド
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64 #ランダムな文字列を生成するRubyのメソッドの一種
      user.name = "ゲスト"
    end
  end

  def guest_user? #メールアドレスがゲストユーザーのものであるかを判定しtrueかfalseの値を返す
    email == GUEST_USER_EMAIL
  end

  def self.looks(search, word)
    if search == "perfect_match"
      User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      User.where("name LIKE?","%#{word}%")
    else
      User.all
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email,:profile_image, :introduction, :is_active)

  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 text-center pt-5">
      <div class="titleG">
        <h1><%= @user.name %>さんのユーザー情報編集</h1>
      </div>
    </div>
  </div>
  <%= form_with model: [:admin, @user], url: admin_user_path(@user.id), method: :patch do |f| %>
    <div class="row justify-content-center">
      <div class="col-3 form-group mt-5 text-center">
        <p>
          ユーザーID
        </p>
      </div>
      <div class="col-5 form-group mt-5 ">
        <%= @user.id %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-3 form-group mt-5 text-center">
        <p>
          ユーザー名
        </p>
      </div>
      <div class="col-5 form-group mt-5 ">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-3 form-group mt-5 text-center">
        <p>
          メールアドレス
        </p>
      </div>
      <div class="col-5 form-group mt-5 ">
          <%= f.text_field :email %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-3 form-group mt-5 ">
        <p>
          ユーザーステータス
        </p>
      </div>
      <div class="col-5 form-group mt-5 ">
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "退会" %>

        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, "有効" %>
      </div>
    </div>
    <div class="form-row justify-content-center">
      <div class="col-5 form-group mt-5">
        <div class="title7">
          <div class="title8">
            <%= f.submit "変更", class: "btn form-control" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-12">
      <div class="col-6 text-center">
        <div class="titleH" >
          <h2>
              ユーザー一覧
          </h2>
        </div>
      </div>
      <div class="pt-5">
        <table class="table", style="color: #4d382e;">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>ユーザー名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td>
                <div class="marker-P-blue">
                  <%= link_to user.name, admin_user_path(user) %>
                </div>
              </td>
              <td><%= user.email %></td>
              <td>
                <% if user.is_active == true %>
                  <p class = "text-success">有効</p>
                <% else%>
                　<p class = "text-secondary">退会済</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col  pt-5">
        <%= paginate @users %>
      </div>
    </div>
  </div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col">
        <div class="col-6 text-center mb-5 mt-3">
          <div class="titleD">
            <h4>
              <%= @user.name %>さんのユーザー詳細
            </h4>
          </div>
        </div>
        <div class="row d-flex justify-content-center">
          <div class="col-12 d-flex align-items-center pl-5">
            <table class="table table-borderless" style="color: #48120E;">
              <tr>
                <th>ユーザーID</td>
                <td><%= @user.id %></td>
              </tr>
              <tr>
                <th>氏名</td>
                <td><%= @user.name %></td>
              </tr>
              <tr>
                <th>メールアドレス</th>
                <td><%= @user.email %></td>
              </tr>
              <tr>
                <th>会員ステータス</th>
                <th><%= @user.is_active %></th>
              </tr>
              <tr>
                <td></td>
                <td class="d-flex justify-content-end">
                  <div class="title7">
                    <div class="title8">
                      <%= link_to "編集する", edit_admin_user_path, class:"btn" %>
                    </div>
                  </div>
                </td>
              </tr>
            </table>
          </div>
        </div>
    </div>
  </div>
</div>