config/routes.rb
Rails.application.routes.draw do
  get 'public/tags'
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
     get "search" => "searches#search"
    resources :users, only: [:index, :show, :edit, :update]
    resources :tags, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
  end

  resources :videos

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :tags, only: [:index, :show]
    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:index, :create, :destroy] do
        get 'post_bookmarks', to: 'bookmarks#index', as: 'user_bookmarks'
      end
    end

    devise_scope :user do
      resources :users, only: [:index, :show, :edit] do
        collection do
          get 'my_page', action: 'mypage'
          patch 'update_my_page', to: 'users#update', as: 'update_user'
          patch :withdraw
          get :bookmark_posts, to: 'bookmarks#index' # ブックマークした一覧
        end
        resource :relationships, only: [:create, :destroy]
        	get "followings" => "relationships#followings", as: "followings"
        	get "followers" => "relationships#followers", as: "followers"

      end

      post "user/guest_sign_in", to: "sessions#guest_sign_in"
    end


    resource :sessions, only: [:new, :create, :destroy]
  end 

end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
      <span class="text-center p-2" style="color: #fef9fb;">
          <i class="fa-solid fa-paw"></i>
      </span>
      <span class="text-center p-2" style="color: #fef9fb;">ポートフォリオ作品　Pet-Diary　近澤絢女</span>
      <span class="text-center p-2" style="color: #fef9fb;">
        <%= link_to new_admin_session_path do %>
          <i class="fa-solid fa-paw"style="color: #fef9fb;"></i>
        <% end %>
      </span>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="fixed-top p-2" style="background-color: #6c2735;">
      <div class="d-flex content-between align-items-center md-4 ">
        <div class="btn-group">
          <%= link_to root_path, class: "btn font-bold", class: "header-logo" do %>
            <%= image_tag '001.png', size: '100x70' %>
          <% end %>
        </div>
        <div class="btn-group pl-5">
          <%# flash.each do |message_type, message| %>
            <div class="flash-message <%#= message_type %>"><%#= message %></div>
          <%# end %>
        </div>
        <div class="btn-group ml-auto">
          <nav class="d-flex align-items-center">
            <ul class="navbar-nav list-group-horizontal ">
              <% if user_signed_in? %>
                  <div class="title1 mr-1">
                    <div class="title2">
                      <li class="nav-item">
                        <%= link_to "マイページ", my_page_users_path, class: "btn font-bold "%>
                      </li>
                    </div>
                  </div>
                  <div class="title1 mr-1">
                    <div class="title2">
                      <li class="nav-item">
                          <%= link_to "新規投稿", new_post_path, class: "btn font-bold "%>
                      </li>
                    </div>
                  </div>
                  <div class="title1 mr-1">
                    <div class="title2">
                      <li class="nav-item">
                        <%= link_to "ユーザー一覧", users_path(id: current_user.id), class: "btn font-bold "%>
                      </li>
                    </div>
                  </div>
                  <div class="title1 mr-1">
                    <div class="title2">
                      <li class="nav-item">
                          <%= link_to "投稿一覧", posts_path, class: "btn font-bold "%>
                      </li>
                    </div>
                  </div>
                  <div class="title1 mr-1">
                    <div class="title2">
                      <li class="nav-item">
                        <%= link_to "タグ", tags_path, class: "btn font-bold "%>
                      </li>
                    </div>
                  </div>
                  <div class="title1 mr-1">
                    <div class="title2">
                      <li class="nav-item">
                        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn font-bold "%>
                      </li>
                    </div>
                  </div>

              <% elsif admin_signed_in? %>
                <% if user_signed_in? && current_user.present? %>
                <% end %>
                <div class="title3">
                  <div class="title4">
                    <li class="nav-item">
                      <%= link_to "ユーザー一覧", admin_users_path, class: "btn font-bold "%>
                    </li>
                  </div>
                </div>
                <div class="title3 ml-1">
                  <div class="title4">
                    <li class="nav-item">
                      <%= link_to "投稿履歴一覧", admin_posts_path, class: "btn font-bold "%>
                    </li>
                  </div>
                </div>
                <div class="title3 ml-1">
                  <div class="title4"> 
                    <li class="nav-item">
                      <%= link_to "タグ一覧", admin_tags_path, class: "btn font-bold "%>
                    </li>
                  </div>
                </div>
                <div class="title3 ml-1">
                  <div class="title4">
                    <li class="nav-item">
                      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn font-bold "%>
                    </li>
                  </div>
                </div>
              <% else %>
                <div class="title5 ml-1">
                  <div class="title6">
                    <li class="nav-item">
                      <%= link_to "新規登録", new_user_registration_path, class: "btn font-bold"%>
                    </li>
                  </div>
                </div>
                <div class="title5 ml-1">
                  <div class="title6">
                    <li class="nav-item">
                      <%= link_to "ログイン", new_user_session_path, class: "btn font-bold"%>
                    </li>
                  </div>
                </div>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" class="h-100">
  <head>
    <title>PetDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Yomogi&display=swap" rel="stylesheet">
    <%#JavaScriptライブラリであるjQueryのスリムバージョンのファイル jQueryは、ウェブページ上でのDOM操作やイベント処理などを簡略化するために使用%>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <%#Bootstrapなどでポップオーバーやドロップダウンメニューの動作に必要なポップパー（位置やサイズを計算するためのライブラリ）を提供するJavaScriptライブラリ%>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <%#BootstrapのJavaScriptファイルであり、Bootstrapのコンポーネントや動作を活用するために使用%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/2a6ea5e69f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100">
      <header class="wrapper">
        <%= render 'layouts/header' %>
      </header>
      <main class="flex-shrink-0">
        <div class="pb-5">
          <div class="search_form pt-3 pb-3">
            <%= render 'public/posts/search' %>
          </div>
          <%= yield %>
        </div>
      </main>
      <footer class="footer  mt-auto py-3" style="background-color: #6c2735 ">
        <%= render 'layouts/footer' %>
      </footer>
  </body>
</html>